%YAML 1.2
--- !<tag:darkgoyle.com,2012:InsuranceUnited>
# data schema for a fictitious insurance company
data:
  policy:
    &status status: draft
    &version version: 0
    &number number:
    region:
      zip:
      city:
    &owner owner:
      gender:
      smoker: false
      pregnant: false
      disabled: false
      birthdate:
      name:
      contact:
        email:
        phone:
    insureds:
      - relationship: self
        ssn:
        member: *owner
    household:
        address:
          street:
          city:
          zip:
        postal:
     
